config/routes.rb
Rails.application.routes.draw do
  get 'say/hello'
  get 'say/goodbye'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
  	@time = Time.now
  end

  def goodbye
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/say/goodbye.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<h1>До свидания!</h1>
	<p>
		Очень приятно, что вы нас навестили.
	</p>
	<p>
		Пора сказать <%= link_to "привет", say_hello_path %>!
	</p>
</body>
</html>

app/views/say/hello.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Rails!</title>
</head>
<body>
<h1>Hello from Rails!</h1>
<p>
	Сейчас <%= @time %>
</p>
<p>
	Пора сказать <%= link_to "до свидания", say_goodbye_path %>!
</p>
</body>
</html>